name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: epn_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, bcmath, pdo, pdo_mysql, xml
        coverage: none

    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: epn/vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('epn/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-interaction
      working-directory: epn

    - name: Copy .env
      run: cp .env.example .env
      working-directory: epn

    - name: Generate app key
      run: php artisan key:generate
      working-directory: epn

    - name: Run migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: epn_test
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan migrate --force
      working-directory: epn

    - name: Run tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: epn_test
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan test
      working-directory: epn
